// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadPacketLoss returns the embedded CollectionSpec for PacketLoss.
func LoadPacketLoss() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PacketLossBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load PacketLoss: %w", err)
	}

	return spec, err
}

// LoadPacketLossObjects loads PacketLoss and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PacketLossObjects
//	*PacketLossPrograms
//	*PacketLossMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPacketLossObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPacketLoss()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PacketLossSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PacketLossSpecs struct {
	PacketLossProgramSpecs
	PacketLossMapSpecs
}

// PacketLossSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PacketLossProgramSpecs struct {
	PathEgress *ebpf.ProgramSpec `ebpf:"path_egress"`
}

// PacketLossMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PacketLossMapSpecs struct {
	SeenSeq     *ebpf.MapSpec `ebpf:"seen_seq"`
	TcpRetrans  *ebpf.MapSpec `ebpf:"tcp_retrans"`
	TcpSegments *ebpf.MapSpec `ebpf:"tcp_segments"`
	ZoneLpm     *ebpf.MapSpec `ebpf:"zone_lpm"`
}

// PacketLossObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPacketLossObjects or ebpf.CollectionSpec.LoadAndAssign.
type PacketLossObjects struct {
	PacketLossPrograms
	PacketLossMaps
}

func (o *PacketLossObjects) Close() error {
	return _PacketLossClose(
		&o.PacketLossPrograms,
		&o.PacketLossMaps,
	)
}

// PacketLossMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPacketLossObjects or ebpf.CollectionSpec.LoadAndAssign.
type PacketLossMaps struct {
	SeenSeq     *ebpf.Map `ebpf:"seen_seq"`
	TcpRetrans  *ebpf.Map `ebpf:"tcp_retrans"`
	TcpSegments *ebpf.Map `ebpf:"tcp_segments"`
	ZoneLpm     *ebpf.Map `ebpf:"zone_lpm"`
}

func (m *PacketLossMaps) Close() error {
	return _PacketLossClose(
		m.SeenSeq,
		m.TcpRetrans,
		m.TcpSegments,
		m.ZoneLpm,
	)
}

// PacketLossPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPacketLossObjects or ebpf.CollectionSpec.LoadAndAssign.
type PacketLossPrograms struct {
	PathEgress *ebpf.Program `ebpf:"path_egress"`
}

func (p *PacketLossPrograms) Close() error {
	return _PacketLossClose(
		p.PathEgress,
	)
}

func _PacketLossClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed packetloss_bpfel.o
var _PacketLossBytes []byte
