// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadPacketLoss returns the embedded CollectionSpec for PacketLoss.
func LoadPacketLoss() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PacketLossBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load PacketLoss: %w", err)
	}

	return spec, err
}

// LoadPacketLossObjects loads PacketLoss and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*PacketLossObjects
//	*PacketLossPrograms
//	*PacketLossMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadPacketLossObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadPacketLoss()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// PacketLossSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PacketLossSpecs struct {
	PacketLossProgramSpecs
	PacketLossMapSpecs
}

// PacketLossSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PacketLossProgramSpecs struct {
	PathEgress *ebpf.ProgramSpec `ebpf:"path_egress"`
}

// PacketLossMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type PacketLossMapSpecs struct {
	BloomBits       *ebpf.MapSpec `ebpf:"bloom_bits"`
	BloomEpoch      *ebpf.MapSpec `ebpf:"bloom_epoch"`
	DebugNoDstZone  *ebpf.MapSpec `ebpf:"debug_no_dst_zone"`
	DebugNoSrcZone  *ebpf.MapSpec `ebpf:"debug_no_src_zone"`
	DebugNotIpv4    *ebpf.MapSpec `ebpf:"debug_not_ipv4"`
	DebugNotTcp     *ebpf.MapSpec `ebpf:"debug_not_tcp"`
	DebugSeen       *ebpf.MapSpec `ebpf:"debug_seen"`
	DebugTcpPayload *ebpf.MapSpec `ebpf:"debug_tcp_payload"`
	DebugTcpPureAck *ebpf.MapSpec `ebpf:"debug_tcp_pure_ack"`
	DebugTcpShort   *ebpf.MapSpec `ebpf:"debug_tcp_short"`
	DebugTcpZoned   *ebpf.MapSpec `ebpf:"debug_tcp_zoned"`
	SrcZoneLpm      *ebpf.MapSpec `ebpf:"src_zone_lpm"`
	StatsRb         *ebpf.MapSpec `ebpf:"stats_rb"`
	ZoneLpm         *ebpf.MapSpec `ebpf:"zone_lpm"`
}

// PacketLossObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadPacketLossObjects or ebpf.CollectionSpec.LoadAndAssign.
type PacketLossObjects struct {
	PacketLossPrograms
	PacketLossMaps
}

func (o *PacketLossObjects) Close() error {
	return _PacketLossClose(
		&o.PacketLossPrograms,
		&o.PacketLossMaps,
	)
}

// PacketLossMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadPacketLossObjects or ebpf.CollectionSpec.LoadAndAssign.
type PacketLossMaps struct {
	BloomBits       *ebpf.Map `ebpf:"bloom_bits"`
	BloomEpoch      *ebpf.Map `ebpf:"bloom_epoch"`
	DebugNoDstZone  *ebpf.Map `ebpf:"debug_no_dst_zone"`
	DebugNoSrcZone  *ebpf.Map `ebpf:"debug_no_src_zone"`
	DebugNotIpv4    *ebpf.Map `ebpf:"debug_not_ipv4"`
	DebugNotTcp     *ebpf.Map `ebpf:"debug_not_tcp"`
	DebugSeen       *ebpf.Map `ebpf:"debug_seen"`
	DebugTcpPayload *ebpf.Map `ebpf:"debug_tcp_payload"`
	DebugTcpPureAck *ebpf.Map `ebpf:"debug_tcp_pure_ack"`
	DebugTcpShort   *ebpf.Map `ebpf:"debug_tcp_short"`
	DebugTcpZoned   *ebpf.Map `ebpf:"debug_tcp_zoned"`
	SrcZoneLpm      *ebpf.Map `ebpf:"src_zone_lpm"`
	StatsRb         *ebpf.Map `ebpf:"stats_rb"`
	ZoneLpm         *ebpf.Map `ebpf:"zone_lpm"`
}

func (m *PacketLossMaps) Close() error {
	return _PacketLossClose(
		m.BloomBits,
		m.BloomEpoch,
		m.DebugNoDstZone,
		m.DebugNoSrcZone,
		m.DebugNotIpv4,
		m.DebugNotTcp,
		m.DebugSeen,
		m.DebugTcpPayload,
		m.DebugTcpPureAck,
		m.DebugTcpShort,
		m.DebugTcpZoned,
		m.SrcZoneLpm,
		m.StatsRb,
		m.ZoneLpm,
	)
}

// PacketLossPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadPacketLossObjects or ebpf.CollectionSpec.LoadAndAssign.
type PacketLossPrograms struct {
	PathEgress *ebpf.Program `ebpf:"path_egress"`
}

func (p *PacketLossPrograms) Close() error {
	return _PacketLossClose(
		p.PathEgress,
	)
}

func _PacketLossClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed packetloss_bpfeb.o
var _PacketLossBytes []byte
